language: java
sudo: required
services:
  - mysql
before_script:
  - mysql -u root -p
  - create database practice;
  - create user 'student'@'%' IDENTIFIED BY '123';
  - GRANT ALL ON *.* TO 'student'@'%';
  - exit;