language: java
sudo: required
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE if not exists practice;" -U postgres
  - psql -c "CREATE USER student WITH PASSWORD '123';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE practice to student;" -U postgres